networks:
  newnet:
    driver: bridge
services:
  mini_server:
    build:
      context: .
    image: miniserver:3.0
    container_name: mini_server
    volumes:  
      - type: bind
        source: './nginx/nginx.conf'              #Проброс файлов конфигурации nginx внутрь контейнера
        target: /etc/nginx/nginx.conf,chmod=755
    networks:
      - 'newnet'                                      
    ports:
      - '8008:81' #Локальный порт для доступа и внутренний соответственно
